### ISSUE TITLE
thank for package, did you plan to improve speed of uuid generation?

### ISSUE THREAD

**Issue by vtolstov** [cbschuld/uuid-base58#1]

**Comment by cbschuld** [comment]
Hi @vtolstov not at this time; curious what you encountered though?  Was it too slow?  Right now I am simply using the canonical uuid v4 solution out there.

**Comment by vtolstov** [comment]
Now it works fine, I'm generate new id for each browser request.
But I'm plan to use it also for all forms. So when user changes some field, new uuid generated and sent

**Comment by cbschuld** [comment]
Thanks @vtolstov - I use it for the same reasons but on the backend in node.  I am going to close this for now - thx!
